apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: default
  labels:
    app: devops 

# ver

spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops

    spec:
      containers:
      - name: devops-demo
        # image: tushar101010/devops-demo:v20250701084804
        image: tushar101010/devops-demo:v20250701084804
        ports:
        - containerPort: 80